In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
from datetime import datetime

Since it is Time Series topic - we shall work with time and dates. :)
Let's create such dataframe.

In [5]:
df_ts = pd.date_range(start="03/06/2020", end="13/06/2020", freq="H") #uztaisa data series pa stundām
df_ts

DatetimeIndex(['2020-03-06 00:00:00', '2020-03-06 01:00:00',
               '2020-03-06 02:00:00', '2020-03-06 03:00:00',
               '2020-03-06 04:00:00', '2020-03-06 05:00:00',
               '2020-03-06 06:00:00', '2020-03-06 07:00:00',
               '2020-03-06 08:00:00', '2020-03-06 09:00:00',
               ...
               '2020-06-12 15:00:00', '2020-06-12 16:00:00',
               '2020-06-12 17:00:00', '2020-06-12 18:00:00',
               '2020-06-12 19:00:00', '2020-06-12 20:00:00',
               '2020-06-12 21:00:00', '2020-06-12 22:00:00',
               '2020-06-12 23:00:00', '2020-06-13 00:00:00'],
              dtype='datetime64[ns]', length=2377, freq='H')

We have data in ISO 8601 format: *yyyy-mm-dd hh:mm:ss*

In [6]:
df_ts = pd.DataFrame(df_ts, columns=["datetime"])
df_ts

                datetime
0    2020-03-06 00:00:00
1    2020-03-06 01:00:00
2    2020-03-06 02:00:00
3    2020-03-06 03:00:00
4    2020-03-06 04:00:00
...                  ...
2372 2020-06-12 20:00:00
2373 2020-06-12 21:00:00
2374 2020-06-12 22:00:00
2375 2020-06-12 23:00:00
2376 2020-06-13 00:00:00

[2377 rows x 1 columns]

When we have a Data Frame - let's populate it with additional data

In [7]:
import numpy as np

df_ts["calls"] = np.random.randint(0, 10, size=(len(df_ts)))
df_ts

                datetime  calls
0    2020-03-06 00:00:00      5
1    2020-03-06 01:00:00      6
2    2020-03-06 02:00:00      0
3    2020-03-06 03:00:00      7
4    2020-03-06 04:00:00      2
...                  ...    ...
2372 2020-06-12 20:00:00      9
2373 2020-06-12 21:00:00      3
2374 2020-06-12 22:00:00      2
2375 2020-06-12 23:00:00      3
2376 2020-06-13 00:00:00      8

[2377 rows x 2 columns]

To address time of any event or fact in table (e.g. number of calls done in each hour) we shall turn *datetime* column into index.

In [ ]:
df_ts = df_ts.set_index("datetime")

In [12]:
df_ts.head()

                     calls
datetime
2020-03-06 00:00:00      5
2020-03-06 01:00:00      6
2020-03-06 02:00:00      0
2020-03-06 03:00:00      7
2020-03-06 04:00:00      2

We already know, that we can iterate via specific dates (since here, datetime is index).

In [13]:
df_ts.loc["2020-03-06 04:00:00"]

calls    2
Name: 2020-03-06 04:00:00, dtype: int64

In [16]:
df_ts.loc["2020-03-06 00:00:00":"2020-03-06 04:00:00"]

                     calls
datetime
2020-03-06 00:00:00      5
2020-03-06 01:00:00      6
2020-03-06 02:00:00      0
2020-03-06 03:00:00      7
2020-03-06 04:00:00      2

Moreover we can do re-sampling.

In [20]:
df_ts.resample("D").sum()

            calls
datetime
2020-03-06    133
2020-03-07    118
2020-03-08    105
2020-03-09     93
2020-03-10    113
...           ...
2020-06-09    121
2020-06-10    111
2020-06-11    106
2020-06-12    125
2020-06-13      8

[100 rows x 1 columns]

In [21]:
df_ts.resample("D").mean()

               calls
datetime
2020-03-06  5.541667
2020-03-07  4.916667
2020-03-08  4.375000
2020-03-09  3.875000
2020-03-10  4.708333
...              ...
2020-06-09  5.041667
2020-06-10  4.625000
2020-06-11  4.416667
2020-06-12  5.208333
2020-06-13  8.000000

[100 rows x 1 columns]

In [22]:
df_ts.resample("T").mean()

                     calls
datetime
2020-03-06 00:00:00    5.0
2020-03-06 00:01:00    NaN
2020-03-06 00:02:00    NaN
2020-03-06 00:03:00    NaN
2020-03-06 00:04:00    NaN
...                    ...
2020-06-12 23:56:00    NaN
2020-06-12 23:57:00    NaN
2020-06-12 23:58:00    NaN
2020-06-12 23:59:00    NaN
2020-06-13 00:00:00    8.0

[142561 rows x 1 columns]

**Resampling frequencies**

- 'min', 'T' - minute
- ‘H’ - hour
- ‘D’ - day
- ‘B’ - business day
- ‘W’ - week
- ‘M’ - month
- ‘Q’ - quarter
- ‘A’ - year